config/routes.rb
Rails.application.routes.draw do
  resources :categories do 
    resources :payments
  end
  devise_for :users
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end  
  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :payments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true

  def total_transaction_amount
    payments.sum(:amount)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_many :category, dependent: :destroy

  validates :name, presence: true, length: { maximum: 25 }
  validates :amount, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/models/payments.rb
class Payment <ApplicationRecord
    belongs :user
    has_many :category, dependent: :destroy

    validates :name, presence: true, length: { maximum: 25 }
    validates :amount, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories, dependent: :destroy
  has_many :payments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = Category.includes(:payments).where(user_id: current_user.id).order(updated_at: :desc)
  end

  # GET /categories/1 or /categories/1.json
  def show
    redirect_to new_category_payment_path(@category)
  end

  # GET /categories/new
  def new
    @category = current_user.categories.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @category = Category.find(params[:category_id])
    @payments = Payment.where(user: current_user, category_id: @category.id).order(updated_at: :desc)
    @total = Payment.where(user: current_user, category_id: @category.id).sum(:amount)
  end

  # GET /payments/1 or /payments/1.json
  def show
    @category = Category.find(params[:category_id])
    @payment = Payment.find(params[:id])
  end

  # GET /payments/new
  def new
    @category = Category.find(params[:category_id])
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user_id = current_user.id
    category = Category.find(params[:category_id])
    @payment.category_id = category.id

    respond_to do |format|
      if @payment.save
        format.html do
          redirect_to category_payments_url(category_id: @payment.category_id),
                      notice: 'Payment was successfully created.'
        end
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def index
      redirect_to categories_path if user_signed_in?
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="categories-list">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>

</div>

app/views/categories/_form.html.erb
<div class="category-header">
     <a href="<%= categories_path %>">
            <i class="fa-solid fa-arrow-left"></i>
        </a>
    <h2>New Category</h2>
    <a href="/logout">
        <i class="fa-solid fa-right-from-bracket"></i>
    </a>
</div>
<%= form_with(model: @category)do |form| %>
    <div class="form-container">
        <%= form.text_field :name, placeholder: "Name" %>
        <%= form.text_field :icon, placeholder: "Icon Link" %>
         <%= form.submit "Create", class: "submit-button" %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show", @category %> |
  <%= link_to "Back", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="category-header">
    <i class="fa-solid fa-bars"></i>
    <h2>My Categories</h2>
    <a href="/logout">
        <i class="fa-solid fa-right-from-bracket"></i>
    </a>
</div>
<div class="categories-container">
    <% if @categories.empty? %>
        <p class="no-data">You have no categories yet.</p>
    <% else %>
        <% @categories.each do |category| %>
            <a href="<%= category_payments_path(category.id) %>">
                <div class="category">
                <img src="<%= category.icon %>" alt="icon" class="category-icon" />
                <p class="cname"><%= category.name %></p>
                <p class="ctotal">Total: $ <%= category.total_transaction_amount %> </p>
                </div>
            </a>
        <% end %>
  <% end %>

    <a href="/categories/new" class="add-category-link">
        <div class="add-category">
            <i class="fa-solid fa-plus"></i>
            <p class="button-name">Add Category</p>
        </div>
    </a>
</div>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<%= link_to "Back", categories_path %>
<%= render @category %>
<div>
  <%= link_to "Edit", edit_category_path(@category) %> |
  <%= button_to "Destroy", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetMate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-proxima-nova@1.0.1/style.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment, url: category_payments_path) do |form| %>
    <div class="header">
    <a href="<%= category_payments_path %>">
        <i class="fa-solid fa-arrow-left"></i>
    </a>
    <p>New Transaction</p>
        <%= form.submit "Create", class: "reg-next" %>
    </div>
    <div class="form-container">
        <%= form.text_field :name, placeholder: "Name" %>
        <%= form.text_field :amount, placeholder: "Amount" %>
    </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

</div>

app/views/payments/index.html.erb
<div class="category-header">
   <a href="<%= categories_path %>">
    <i class="fa-solid fa-arrow-left"></i>
  </a>
    <h2>My Transactions</h2>
    <a href="/logout">
        <i class="fa-solid fa-right-from-bracket"></i>
    </a>
</div>


<div id="payments">

<% if @payments.empty? %>
      <p class="no-data">No transactions here yet.</p>
    <% else %>
  <% @payments.each do |payment| %>
  <div class="single-payment">
      <p class="payment-name"><%= payment.name %></p>
      <p>Price: $ <%= payment.amount %> </p>
    </div>
  <% end %>
  <% end %>

        <div class="add-category-link">     
            <div class="add-category">
            <i class="fa-solid fa-plus"></i>
             <%= link_to "Add Transaction", new_category_payment_path %>
             </div>
        </div>

</div>

app/views/payments/new.html.erb
<div class="category-header">
     <a href="<%= categories_path %>">
            <i class="fa-solid fa-arrow-left"></i>
        </a>
    <h2>New Transaction</h2>
    <a href="/logout">
        <i class="fa-solid fa-right-from-bracket"></i>
    </a>
</div>

<%= form_with(model: @payment, url: category_payments_path) do |form| %>
   
<div class="form-container">
        <%= form.text_field :name, placeholder: "Name" %>
        <%= form.text_field :amount, placeholder: "Amount" %>
         <%= form.submit "Create", class: "submit-button" %>
    </div>
<% end %>

app/views/payments/show.html.erb
<%= render @payment %>

<div>
  <%= link_to "Edit", edit_payment_path(@payment) %> |
  <%= link_to "Back", payments_path %>

  <%= button_to "Destroy", @payment, method: :delete %>
</div>

app/views/users/index.html.erb
<div class="splash-container">
<h1 class="title">Budget Mate</h1>
<h4 class="sub-title">Catalog your transactions</h4>
<div class="buttons">
    <%= link_to "LOG IN" , new_user_session_path , class: "signin button" %>
    <%= link_to "SIGN UP" , new_user_registration_path , class: "signup button"%>
</div>

</div>